name: front_admin
description: Testing the resource server
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  dio:
  http: ^0.13.5
  universal_io: ^2.2.0
  http_pro:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

